---
- name: Joo. Install desktop environment
  hosts: all
  gather_facts: no

  vars:
    cask_packages:
      - adobe-acrobat-reader
      - firefox
      - flowdock
      - google-chrome
      - graphiql
      - intellij-idea
      - iterm2
      - postico
      - secure-pipes
      - shiftit
      - skype
      - visual-studio-code

  tasks:
    - name: Install Homebrew Cask packages
      homebrew_cask: name={{ item }} state=present
      with_items: "{{ cask_packages }}"

