---
- name: Setup homebrew taps
  hosts: all
  gather_facts: no

  vars:
    taps:
      - caskroom/versions
      - homebrew/versions

  tasks:
    - name: Add Homebrew taps
      homebrew_tap: name={{ item }} state=present
      with_items: "{{ taps }}"
